# Generated by Django 2.2.2 on 2019-07-02 22:26

import django.core.validators
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('abandoned', 'abandoned'), ('in development', 'in development'), ('maintained', 'maintained'), ('on draft', 'on draft'), ('complete', 'complete')], default='abandoned', max_length=100, no_check_for_status=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vacant_slots', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(128)])),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3092)),
            ],
        ),
    ]
