# Generated by Django 2.2.2 on 2019-06-29 18:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('abandoned', 'abandoned'), ('in development', 'in development'), ('maintained', 'maintained'), ('on draft', 'on draft'), ('complete', 'complete')], default='abandoned', max_length=100, no_check_for_status=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contributors', models.ManyToManyField(related_name='project_project_participant', to=settings.AUTH_USER_MODEL)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_project_leader', to=settings.AUTH_USER_MODEL)),
                ('repos', models.ManyToManyField(to='projects.Repository')),
            ],
        ),
    ]
