# Generated by Django 2.2.2 on 2019-07-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='project_project_participant', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_project_leader', to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='repos',
            field=models.ManyToManyField(to='projects.Repository'),
        ),
    ]
