# Generated by Django 2.2.2 on 2019-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='repo_id',
            field=models.IntegerField(default=-1),
        ),
    ]
