# Generated by Django 2.2.2 on 2019-06-29 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20190629_2143'),
        ('projects', '0003_auto_20190629_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='url',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='user',
        ),
        migrations.AddField(
            model_name='repository',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='repository',
            name='description',
            field=models.TextField(default='', max_length=3092),
        ),
        migrations.AddField(
            model_name='repository',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='project_project_participant', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_project_leader', to='user_profile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repo_id',
            field=models.IntegerField(),
        ),
    ]
