# Generated by Django 2.2.2 on 2019-07-03 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190702_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
    ]
